[tool.poetry]
name = "pyasic-web"
version = "0.1.0"
description = ""
authors = ["UpstreamData <brett@upstreamdata.ca>"]
readme = "README.md"
packages = [{include = "pyasic_web"}]

[tool.poetry.dependencies]
python = "^3.8"
pyasic = "*"
websockets = "^10.4"
uvicorn = "^0.20.0"
starlette = "*"
python-multipart = "^0.0.5"
imia = "^0.5.3"
itsdangerous = "2.1.2"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
djlint = "^1.19.17"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
