[tool.poetry]
name = "pyasic-web"
version = "0.1.0"
description = ""
authors = ["UpstreamData <brett@upstreamdata.ca>"]
readme = "README.md"
packages = [{include = "pyasic_web"}]

[tool.poetry.dependencies]
python = "^3.8"
pyasic = "*"
websockets = "^10.4"
fastapi = {extras = ["uvicorn"], version = "^0.89.1"}
uvicorn = "^0.20.0"
python-multipart = "^0.0.5"
fastapi-login = "^1.8.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
